### ISSUE TITLE
Not working with Swift

### ISSUE THREAD

**Issue by kishinmanglani** [stripe/ApplePayStubs#14]
My apple pay implementation is working well. When I substitute the apple pay controller with STPTestPaymentAuthorizationViewController it doesn't work. I get a view with a cancel button but the rest is empty/see transparent. As far as I can tell, the tableView, buttons, etc. are all nil. I'm using swift and cocoapods.

Bridging header: `#import <ApplePayStubs/STPTestPaymentAuthorizationViewController.h>`

**Comment by Artwalk** [comment]
I think you new an pure swift project.  
So, you should new an `objective-c` files(.h .m) in your project, and then del the `pod` directory, and  `pod update`.

It worked on mine :)

**Comment by jflinter** [comment]
#15 should resolve this.
